/**
 * MFA-related types for authentication flow.
 *
 * Response types use snake_case to match Auth0 API conventions.
 * SDK-facing types use camelCase.
 */

import type { MfaRequirements } from "../errors/index.js";

/** @ignore */
export interface AuthenticatorApiResponse {
  id: string;
  authenticator_type: string;
  type?: string;
  active: boolean;
  name?: string;
  phone_number?: string;
  oob_channel?: string;
  created_at?: string;
  last_auth?: string;
}

/** @ignore */
export interface ChallengeApiResponse {
  challenge_type: string;
  oob_code?: string;
  binding_method?: string;
}

/** @ignore */
export interface EnrollmentApiResponse {
  authenticator_type: "otp" | "oob" | "email";
  id: string;
  recovery_codes?: string[];
  secret?: string;
  barcode_uri?: string;
  oob_channel?: "sms" | "voice" | "auth0" | "email";
  name?: string;
  oob_code?: string;
  binding_method?: string;
}

/** @ignore */
export interface VerifyCredentialBody {
  otp?: string;
  oobCode?: string;
  bindingCode?: string;
  recoveryCode?: string;
}

/** @ignore */
export const GRANT_TYPE_MFA_OTP = "http://auth0.com/oauth/grant-type/mfa-otp";

/** @ignore */
export const GRANT_TYPE_MFA_OOB = "http://auth0.com/oauth/grant-type/mfa-oob";

/** @ignore */
export const GRANT_TYPE_MFA_RECOVERY_CODE =
  "http://auth0.com/oauth/grant-type/mfa-recovery-code";

/**
 * Raw token response from `auth0.mfa.verify()`. Uses snake_case to match Auth0 API conventions.
 *
 * @group Server
 * @title MFA Verify Response
 * @order 120
 */
export interface MfaVerifyResponse {
  /** Access token */
  access_token: string;
  /** Refresh token (if present) */
  refresh_token?: string;
  /** ID token (if present) */
  id_token?: string;
  /** Token type (usually "Bearer") */
  token_type: string;
  /** Token scope */
  scope?: string;
  /** API audience */
  audience?: string;
  /** Expires in seconds */
  expires_in: number;
  /** Recovery code (if regenerated by tenant config) */
  recovery_code?: string;
}

/**
 * Options for enrolling an OTP (TOTP) authenticator via `auth0.mfa.enroll()`.
 *
 * @group Server
 * @title Enroll OTP Options
 * @order 62
 */
export interface EnrollOtpOptions {
  /** Encrypted MFA token */
  mfaToken: string;
  /** Authenticator types to enroll */
  authenticatorTypes: ["otp"];
}

/**
 * Options for enrolling an OOB (SMS/Voice/Push/Email) authenticator via `auth0.mfa.enroll()`.
 *
 * @group Server
 * @title Enroll OOB Options
 * @order 63
 */
export interface EnrollOobOptions {
  /** Encrypted MFA token */
  mfaToken: string;
  /** Authenticator types to enroll */
  authenticatorTypes: ["oob"];
  /** OOB channels (sms, voice, auth0, email) */
  oobChannels: ("sms" | "voice" | "auth0" | "email")[];
  /** Phone number in E.164 format (required for sms/voice) */
  phoneNumber?: string;
  /** Email address (optional for email channel) */
  email?: string;
}

/**
 * MFA enrollment options passed to `auth0.mfa.enroll()`. Discriminated union of
 * `EnrollOtpOptions` and `EnrollOobOptions`.
 *
 * @group Server
 * @title Enroll Options
 * @order 61
 */
export type EnrollOptions = EnrollOtpOptions | EnrollOobOptions;

/** @ignore */
export interface OtpEnrollmentResponse {
  authenticatorType: "otp";
  secret: string;
  barcodeUri: string;
  recoveryCodes?: string[];
  id: string;
}

/** @ignore */
export interface OobEnrollmentResponse {
  authenticatorType: "oob";
  oobChannel: "sms" | "voice" | "auth0" | "email";
  recoveryCodes?: string[];
  id: string;
  name?: string;
  oobCode?: string;
  bindingMethod?: string;
  barcodeUri?: string;
}

/**
 * Response from `auth0.mfa.enroll()`. Discriminated union by `authenticatorType`.
 * Contains enrollment details including TOTP secret/barcode URI (OTP) or OOB code (SMS/Push).
 *
 * @group Server
 * @title Enrollment Response
 * @order 64
 */
export type EnrollmentResponse = OtpEnrollmentResponse | OobEnrollmentResponse;

/**
 * The `auth0.mfa` client interface. Access via `auth0.mfa` on an `Auth0Client` instance.
 * Use this to drive MFA challenge-response and enrollment flows after receiving a `MfaRequiredError`.
 *
 * @group Server
 * @title MFA Client
 * @order 57
 */
export interface MfaClient {
  /**
   * List enrolled authenticators for the user.
   * @param options - Options containing encrypted mfaToken.
   */
  getAuthenticators(options: { mfaToken: string }): Promise<Authenticator[]>;

  /**
   * Initiate an MFA challenge.
   * @param options - Challenge options including mfaToken, challengeType, and optional authenticatorId.
   */
  challenge(options: {
    mfaToken: string;
    challengeType: string;
    authenticatorId?: string;
  }): Promise<ChallengeResponse>;

  /**
   * Verify MFA code and complete authentication.
   * @param options - Verification options: `otp`, `oobCode + bindingCode`, or `recoveryCode`.
   */
  verify(options: VerifyMfaOptions): Promise<MfaVerifyResponse>;

  /**
   * Enroll a new MFA authenticator.
   * @param options - Enrollment options for OTP or OOB authenticator.
   */
  enroll(options: EnrollOptions): Promise<EnrollmentResponse>;
}

/**
 * An enrolled MFA authenticator returned by `auth0.mfa.getAuthenticators()`.
 *
 * @group Server
 * @title Authenticator
 * @order 58
 */
export interface Authenticator {
  /** Authenticator ID */
  id: string;
  /** Authenticator type (e.g., 'otp', 'oob') */
  authenticatorType: string;
  type?: string;
  /** Whether this authenticator is active */
  active: boolean;
  name?: string;
  phoneNumber?: string;
  oobChannel?: string;
  createdAt?: string;
  lastAuthenticatedAt?: string;
}

/**
 * Response from `auth0.mfa.challenge()`.
 *
 * @group Server
 * @title Challenge Response
 * @order 59
 */
export interface ChallengeResponse {
  /** Challenge type (otp, oob) */
  challengeType: string;
  /** OOB code (for oob challenges) */
  oobCode?: string;
  /** Binding method (for oob challenges, e.g., 'prompt') */
  bindingMethod?: string;
}

/**
 * Base options for `auth0.mfa.verify()`. Extended by each verification method.
 *
 * @group Server
 * @title Verify MFA Options Base
 * @order 65
 */
export interface VerifyMfaOptionsBase {
  /** Encrypted MFA token */
  mfaToken: string;
}

/**
 * Verification with OTP code from an authenticator app (TOTP).
 *
 * @group Server
 * @title Verify MFA With OTP Options
 * @order 66
 */
export interface VerifyMfaWithOtpOptions extends VerifyMfaOptionsBase {
  /** 6-digit OTP code from authenticator app */
  otp: string;
}

/**
 * Verification with OOB code sent via SMS/Email/Push.
 *
 * @group Server
 * @title Verify MFA With OOB Options
 * @order 67
 */
export interface VerifyMfaWithOobOptions extends VerifyMfaOptionsBase {
  /** OOB code from `challenge()` response */
  oobCode: string;
  /** Binding code received via SMS/Push */
  bindingCode: string;
}

/**
 * Verification with a recovery code.
 *
 * @group Server
 * @title Verify MFA With Recovery Code Options
 * @order 68
 */
export interface VerifyMfaWithRecoveryCodeOptions extends VerifyMfaOptionsBase {
  /** Recovery code from enrollment */
  recoveryCode: string;
}

/**
 * Options for `auth0.mfa.verify()`. Discriminated union: pass `otp`, `oobCode + bindingCode`,
 * or `recoveryCode` depending on the challenge type.
 *
 * @group Server
 * @title Verify MFA Options
 * @order 60
 */
export type VerifyMfaOptions =
  | VerifyMfaWithOtpOptions
  | VerifyMfaWithOobOptions
  | VerifyMfaWithRecoveryCodeOptions;

/** @ignore */
export interface MfaContext {
  mfaToken: string;
  audience: string;
  scope: string;
  mfaRequirements: MfaRequirements | undefined;
  createdAt: number;
}
